name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-interaction

    - name: Run PHPStan (Analyse Statique)
      run: |
        vendor/bin/phpstan analyse

    - name: Run PHPUnit Tests
      run: |
        vendor/bin/phpunit --prefer-dist --no-interaction

    - name: Build Docker Image
      run: |
        docker build -t my-php-app .

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag my-php-app mydockerhubusername/my-php-app:latest
        docker push mydockerhubusername/my-php-app:latest

    - name: Deploy to Production (Docker)
      run: |
        ssh user@your-server-ip 'docker pull mydockerhubusername/my-php-app:latest && docker-compose up -d'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
